name: LP Capital Management
favicon: null
layout_spectrum: 0.93048
typography_spectrum: 0.3791912654414773
title: LP Capital Management
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0
  lightness: 0.7862878609448671
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
